import type { Metadata } from "next";
import "../../globals.css";
import { Sidebar } from "@/domain/dashboard/components/Sidebar";
import { Providers } from "@/app/(main)/Providers";

export const metadata: Metadata = {
  title: "Kalita - Developement Website",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <Providers>
              <body className="flex">
        <Sidebar />
          <div className="w-full bg-kalita-portfolio">
            {children}
          </div>
      </body>
      </Providers>

    </html>
  );
}
